#!/bin/sh
set -eu

input_list=
output=
log=
while [ "$#" -gt 0 ]; do
  case "$1" in
    --input)
      input_list=$2
      shift 2
      ;;
    --output)
      output=$2
      shift 2
      ;;
    --log)
      log=$2
      shift 2
      ;;
    *)
      shift
      ;;
  esac
done

test -n "$input_list"
test -n "$output"
: > "$output"
while IFS= read -r chunk; do
  cat "$chunk" >> "$output"
done < "$input_list"
if [ -n "$log" ]; then
  printf 'ligate fixture\n' > "$log"
fi
