#!/bin/sh
set -eu

output=
log=
while [ "$#" -gt 0 ]; do
  case "$1" in
    --output)
      output=$2
      shift 2
      ;;
    --log)
      log=$2
      shift 2
      ;;
    *)
      shift
      ;;
  esac
done

test -n "$output"
printf '0 chr1 chr1:1-200 chr1:50-150\n' > "$output"
if [ -n "$log" ]; then
  printf 'chunk fixture\n' > "$log"
fi
