#!/bin/sh
set -eu

input_region=
output_prefix=
log=
while [ "$#" -gt 0 ]; do
  case "$1" in
    --input-region)
      input_region=$2
      shift 2
      ;;
    --output)
      output_prefix=$2
      shift 2
      ;;
    --log)
      log=$2
      shift 2
      ;;
    *)
      shift
      ;;
  esac
done

test -n "$input_region"
test -n "$output_prefix"
region_token=$(printf '%s' "$input_region" | tr ':-' '__')
printf 'binary reference fixture\n' > "${output_prefix}_${region_token}.bin"
if [ -n "$log" ]; then
  printf 'split reference fixture\n' > "$log"
fi
